"""removed id row

Revision ID: 22057c3c3012
Revises: ff7008c64dff
Create Date: 2022-02-24 21:34:05.846481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22057c3c3012'
down_revision = 'ff7008c64dff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Leads', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Leads', sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Leads_id_seq"\'::regclass)'), autoincrement=True, nullable=False))
    # ### end Alembic commands ###
